export { default as HomeView } from './HomeView'
export { default as RegisterView } from './RegisterView'
export { default as LoginView } from './LoginView'
export { default as UserView } from './UserView'
export { default as AdminView } from './AdminView'
export { default as PropertyView } from './PropertyView'
export { default as CartView } from './CartView'
export { default as NotFound } from './NotFound'