export { default as HomeView } from './HomeView'
export { default as RegisterView } from './RegisterView'
export { default as SesionView } from './SesionView'
export { default as UserView } from './UserView'
export { default as PropertyView } from './PropertyView'
export { default as NotFound } from './NotFound'